config/routes.rb
Rails.application.routes.draw do

get "signup", to: "messages#new"
post "signup", to: "messages#create"
get "login", to: "sessions#new"

post "login", to: "sessions#create"

delete "logout", to: "sessions#destroy"
get "logout", to: "sessions#destroy"
post "signup", to: "messages#create"
get  "signin", to: "chatrooms#new"
post  "signin", to: "chatrooms#create"
mount ActionCable.server => '/cable'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
belongs_to :user
validates :body, presence: true
scope :custom_display, -> {order(:created_at).last(10)}

end

app/models/user.rb
class User < ApplicationRecord
has_many :messages
validates :username, presence: true, length: {maximum: 15, minimum: 3}, uniqueness: true
has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
helper_method :current_user,:logged_in?
def current_user
@current_user ||= @user = User.find(session[:user_id]) if session[:user_id]
end
def logged_in?
!! current_user
end
def require_user
if !logged_in?
flash[:error] = "You are not logged in to perform this action"
redirect_to login_path
end
end
end

app/controllers/chatrooms_controller.rb
class ChatroomsController < ApplicationController
#before_action :require_user , only: [:index]

def new
@user = User.new


end
def create
@user = User.new(user_params)
if @user.save
session[:user_id] = @user.id
flash[:success] = "welcome"
ConfirmMailer.confirmation(current_user).deliver_now
redirect_to signup_path
else
render :new
end
end
private
def user_params
params.require(:user).permit(:username, :password)
end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
before_action :require_user, only: [:new,:create]
def new
@message = Message.new
@messages = Message.custom_display
end

def create
@message = Message.new(message_params)
@message.user = current_user
if @message.save
flash[:success]= "great is your name lord"
ConfirmMailer.confirmation(current_user).deliver_now
ActionCable.server.broadcast "message_channel",  
                              body: @message.body, user: @message.user.username
redirect_to signup_path 
end
end

def index

end



private
def message_params
params.require(:message).permit(:body)

end




end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
before_action :logged_in_redirect ,only:[:new,:create]
def new


end
def create
user = User.find_by(username: params[:session][:username])
if user && user.authenticate(params[:session][:password])
session[:user_id] = user.id
flash[:success] = "you have sucessfully logged in"
redirect_to signup_path
else
flash.now[:error] = "Login information not correct"
render :new
end
end
def destroy
session[:user_id] = nil
flash[:error] = "you are logged out"
redirect_to login_path
end
private
 def logged_in_redirect
 if logged_in?
 flash[:success] = "You are already logged in"
 redirect_to signup_path
 end
end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/chatrooms/new.html.erb
<div class="ui two column very relaxed stackable grid ">
    <div class="column">
     <%= form_for(:user, :html => {class: "form-horizontal", role: "form"}) do |f|%>
     <div class="field ">
     <%= f.label :username %>
     <%= f.text_field :username, class: "form-control",  placeholder: "Name of the user", autofocus: true %>
    </div>
     
        <div class="field ">
     <%= f.label :password %> <br/>
     <%= f.password_field :password, class: "form-control", placeholder: "password" %>
	</div>

     <%= f.submit "Sign up", class: "btn btn-primary btn-lg"%>
	 <% end %>
    
  </div>
 
</div>

app/views/layouts/_flashmessage.html.erb
<% flash.each do |name,msg| %>
<div class="ui <%= name %> message transition">
  <i class="close icon"></i>
  <div class="header">
  <%= msg %>
</div>
</div>
<% end %>

app/views/layouts/_navigation.html.erb
<div class="ui small inverted menu">

<div class="ui container">
  <a class=" item">
  <% if logged_in? %>
   <%= link_to "Chatroom", signup_path, class: "button"%>
   <% end %>
  </a>
  <a class="item">
    Messages
  </a>
  
   
	<div class="right menu">
	<% if logged_in? %>
	<%= link_to "logout", logout_path,method: :delete, class: "button"%>
	<% else %>
	<%= link_to "login", login_path, class: "button"%>
    <div class="item">
        <div class="ui primary button">Sign Up</div>
    </div>
	<% end %>
   </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
  
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<%=  render "layouts/navigation" %>
<%= render "layouts/flashmessage" %>
    <%= yield %>
  </body>
</html>

app/views/messages/new.html.erb
<% if @message.errors.any? %>
<div class="row">
<div class="errormessages">
</h4>
<%= pluralize(@mesage.errors.count, "error") %>
prohibited this message from being saved </h4>
<ul>
<% @message.errors.full_messages.each do |msg| %>
<li> <%= msg %> </li>
<% end %>
</ul>
</div>
</div>
<% end %>

<h1 class="center"> Messages in the chatroom </h1>
<h2 class="ui center aligned medium icon header">
 <i class="address book orange outline icon"></i>
  Chatroom
</h2>
<div class="ui equal width grid">
 <div class="twelve wide column">
  <div class="ui fluid raised card chatbox" id="height" >
   <div class="content">
    <div class="ui large feed">
	
     <div class="event" id="event2" >
	 <% @messages.each do |message| %>
	 
	<p> <%= message.user.username%>:
	<%=  message.body %> </p>
   
     
    
      
      
    <% end %>
    </div>
	
	<div class="extra content" >
	<%= form_for(:message, :html => {class: "ui reply form ", role: "form"}) do |f| %>
        <div class="field">
		<%= f.text_field :body %>
        <%= f.submit class: "bordered inverted  orange" %>
        </div>
      <% end %>
   </div>
  </div> 
</div>
</div>



   
		
  